@echo off
setlocal enabledelayedexpansion

REM 获取最新的 Stock_V* tag
for /f "tokens=*" %%a in ('git describe --tags --abbrev^=0 --match "Stock_V*" 2^>nul') do set TAG=%%a

REM 如果没有找到 tag，使用默认版本
if "%TAG%"=="" set TAG=Stock_V1.0

REM 提取版本号 (Stock_V1.19 -> 1.19)
set VERSION=%TAG:Stock_V=%

REM 分割主版本号和次版本号
for /f "tokens=1,2 delims=." %%a in ("%VERSION%") do (
    set MAJOR=%%a
    set MINOR=%%b
)

REM 如果没有次版本号，设为0
if "%MINOR%"=="" set MINOR=0

REM 生成头文件
echo // Auto-generated by GenerateVersion.bat > "%~dp0StockVersion.h"
echo // Do not edit manually >> "%~dp0StockVersion.h"
echo #pragma once >> "%~dp0StockVersion.h"
echo. >> "%~dp0StockVersion.h"
echo #define STOCK_VERSION_MAJOR %MAJOR% >> "%~dp0StockVersion.h"
echo #define STOCK_VERSION_MINOR %MINOR% >> "%~dp0StockVersion.h"
echo #define STOCK_VERSION_STR L"%VERSION%" >> "%~dp0StockVersion.h"
echo #define STOCK_VERSION_RC %MAJOR%,%MINOR%,0,0 >> "%~dp0StockVersion.h"
echo #define STOCK_VERSION_RC_STR "%VERSION%.0.0" >> "%~dp0StockVersion.h"

echo Generated StockVersion.h with version %VERSION%
