// Auto-generated by GenerateVersion.bat
// Do not edit manually
#pragma once

#define STOCK_VERSION_MAJOR 1
#define STOCK_VERSION_MINOR 26
#define STOCK_VERSION_STR L"1.26"
#define STOCK_VERSION_RC 1,26,0,0
#define STOCK_VERSION_RC_STR "1.26.0.0"
